### ISSUE TITLE
Dec 7 papers

### ISSUE THREAD

**Issue by grburgess** [grburgess/awesome-reading-group#5] opened 2020-11-30 07:51 UTC
### Model independent calibrations of gamma ray bursts using machine learning

https://arxiv.org/abs/2011.13590

We alleviate the circularity problem, whereby gamma-ray bursts are not perfect distance indicators, by means of a new model-independent technique based on Bézier polynomials. To do so, we use the well consolidate \textit{Amati} and \textit{Combo} correlations. We consider improved calibrated catalogs of mock data from differential Hubble rate points. To get our mock data, we use those machine learning scenarios that well adapt to gamma ray bursts, discussing in detail how we handle small amounts of data from our machine learning techniques. In particular, we explore only three machine learning treatments, i.e. \emph{linear regression}, \emph{neural network} and \emph{random forest}, emphasizing quantitative statistical motivations behind these choices. Our calibration strategy consists in taking Hubble's data, creating the mock compilation using machine learning and calibrating the aforementioned correlations through Bézier polynomials with a standard chi-square analysis first and then by means of a hierarchical Bayesian regression procedure. The corresponding catalogs, built up from the two correlations, have been used to constrain dark energy scenarios. We thus employ Markov Chain Monte Carlo numerical analyses based on the most recent Pantheon supernova data, baryonic acoustic oscillations and our gamma ray burst data. We test the standard ΛCDM model and the Chevallier-Polarski-Linder parametrization. We discuss the recent H0 tension in view of our results. Moreover, we highlight a further severe tension over Ωm and we conclude that a slight evolving dark energy model is possible.

#### Comments:
well.

**Comment by grburgess** [comment] 2020-11-30 07:59
### A Coincidence Null Test for Poisson-Distributed Events

https://arxiv.org/abs/2011.13787

When transient events are observed with multiple sensors, it is often necessary to establish the significance of coincident events. We derive a universal null test for an arbitrary number of sensors motivated by the archetypal detection problem for independent Poisson-distributed events in gravitational-wave detectors such as LIGO and Virgo. In these detectors, transient events may be witnessed by myriad channels that record interferometric signals and the surrounding physical environment. We apply our null test to a broad set of simulated gravitational-wave events as well as to a real gravitational-wave detection to determine which auxiliary channels do and do not witness real gravitational waves, and therefore which are safe to use when constructing vetoes. We also describe how our approach can be used to study detector artifacts and their origin, as well as to quantify the statistical independence of candidate GW signals from noise artifacts observed in auxiliary channels.

#### Comments:

Useful for association.

**Comment by grburgess** [comment] 2020-12-01 06:42
### Constraining the intrinsic population of Long Gamma-Ray Bursts: implications for spectral correlations, cosmic evolution and their use as tracers of star formation

https://arxiv.org/abs/2011.14745

Long Gamma-Ray Bursts (LGRBs) have been shown to be powerful probes of the Universe, in particular to study the star formation rate up to very high redshift (z∼9). Since LGRBs are produced by only a small fraction of massive stars, it is paramount to have a good understanding of their underlying intrinsic population in order to use them as cosmological probes without introducing any unwanted bias. The goal of this work is to constrain and characterise this intrinsic population. We developed a Monte Carlo model where each burst is described by its redshift and its properties at the peak of the lightcurve. We derived the best fit parameters by comparing our synthetic populations to carefully selected observational constraints based on the CGRO/BATSE, Fermi/GBM and Swift/BAT samples with appropriate flux thresholds. We explored different scenarios in terms of cosmic evolution of the luminosity function and/or of the redshift distribution as well as including or not the presence of intrinsic spectral-energetics (Ep-L) correlations. We find that the existence of an intrinsic Ep-L correlation is preferred but with a shallower slope than observed(αA∼0.3) and a larger scatter (∼0.4 dex). We find a strong degeneracy between the cosmic evolution of the luminosity and of the LGRB rate, and show that a sample both larger and deeper than SHOALS by a factor of three is needed to lift this degeneracy. The observed We conclude that Ep-L correlation cannot be explained only by selection effects although these do play a role in shaping the observed relation. The degeneracy between cosmic evolution of the luminosity function and of the redshift distribution of LGRBs should be included in the uncertainties of star formation rate estimates; these amount to a factor of 10 at z=6 and up to a factor of 50 at z=9.

### Comments:

A very long and frustrated sigh. This is wrong on many, many, many levels. None of the multi-level Bayes.

**Comment by grburgess** [comment] 2020-12-01 07:46
### The Optical Luminosity-Time Correlation for More Than 100 Gamma-Ray Burst Afterglows

https://arxiv.org/abs/2011.14493

Gamma-Ray Bursts (GRBs) are fascinating events due to their panchromatic nature. Their afterglow emission is observed from sub-TeV energies to radio wavelengths. We investigate GRBs that present an optical plateau, leveraging on the resemblance with the X-ray plateau shown in many GRB light curves (LCs). We comprehensively analyze all published GRBs with known redshifts and optical plateau observed mostly by the Neil Gehrels Swift Observatory (Swift). We fit 267 optical LCs and show the existence of the plateau in 102 cases, which is the largest compilation so far of optical plateaus. For 56 Swift GRBs with optical and X-ray plateaus, we compare the rest-frame end time at both wavelengths (T*_opt , T*_X), and conclude that the plateau is achromatic between T*_opt and T*_X. We also confirm the existence of the two-dimensional relations between T*_opt and the optical luminosity at the end of the plateau emission, which resembles the same luminosity-time correlation in X-rays (Dainotti et al. 2013). The existence of this optical correlation has been demonstrated for the largest sample of optical plateaus in the literature to date. The squared scatter in this optical correlation is smallest for the subset of the Gold GRBs with a decrease in the scatter equivalent to 52.4% when compared to the scatter of the entire GRB sample.

#### Comments: 
Correlations.

**Comment by grburgess** [comment] 2020-12-01 07:48
### Accelerating MCMC algorithms through Bayesian Deep Networks

https://arxiv.org/abs/2011.14276

Markov Chain Monte Carlo (MCMC) algorithms are commonly used for their versatility in sampling from complicated probability distributions. However, as the dimension of the distribution gets larger, the computational costs for a satisfactory exploration of the sampling space become challenging. Adaptive MCMC methods employing a choice of proposal distribution can address this issue speeding up the convergence. In this paper we show an alternative way of performing adaptive MCMC, by using the outcome of Bayesian Neural Networks as the initial proposal for the Markov Chain. This combined approach increases the acceptance rate in the Metropolis-Hasting algorithm and accelerate the convergence of the MCMC while reaching the same final accuracy. Finally, we demonstrate the main advantages of this approach by constraining the cosmological parameters directly from Cosmic Microwave Background maps.


#### Comments:

Not really something we should spend time on.

**Comment by grburgess** [comment] 2020-12-01 07:56
### Probing UHECR production in Centaurus A using secondary neutrinos and gamma-rays

https://arxiv.org/abs/2011.13984

In this paper the production of neutrinos and photons by ultra high energy cosmic rays (UHECR) interacting with the extragalactic background radiation is studied. Centaurus A is assumed as the prime source of UHECR and the possibility to identify this source by detecting the secondary neutrinos and photons produced in the propagation is investigated. Fifteen astrophysical models regarding three extragalactic magnetic fields (EGMF) and five composition abundances are simulated. The results show that the possibility of detection depends highly on the astrophysical model considered, specially the intensity of the magnetic field. The flux and arrival direction are investigated. The possibility to detected Cen A as a point source and the potentiality for an anisotropic signal are evaluated. For some combinations of EGMF and composition, Cen A could be identified by future experiments by the detection of secondary neutrinos in the energy range from 1014 to 1017 eV.

#### Comments:

I will likely not read this.

**Comment by cescalara** [comment] 2020-12-03 07:05
### A search for time-dependent astrophysical neutrino emission with IceCube data from 2012 to 2017

https://arxiv.org/abs/2012.01079

High-energy neutrinos are unique messengers of the high-energy universe, tracing the processes of cosmic-ray acceleration. This paper presents analyses focusing on time-dependent neutrino point-source searches. A scan of the whole sky, making no prior assumption about source candidates, is performed, looking for a space and time clustering of high-energy neutrinos in data collected by the IceCube Neutrino Observatory between 2012 and 2017. No statistically significant evidence for a time-dependent neutrino signal is found with this search during this period since all results are consistent with the background expectation. Within this study period, the blazar 3C 279, showed strong variability, inducing a very prominent gamma-ray flare observed in 2015 June. This event motivated a dedicated study of the blazar, which consists of searching for a time-dependent neutrino signal correlated with the gamma-ray emission. No evidence for a time-dependent signal is found. Hence, an upper limit on the neutrino fluence is derived, allowing us to constrain a hadronic emission model.

#### Comments

**Comment by cescalara** [comment] 2020-12-03 07:07
### Fast, flexible, and accurate evaluation of Malmquist bias with machine learning: Preparing for the pending flood of gravitational-wave detections

https://arxiv.org/abs/2012.01317

Many astronomical surveys are limited by the brightness of the sources, and gravitational-wave searches are no exception. The detectability of gravitational waves from merging binaries is affected by the mass and spin of the constituent compact objects. To perform unbiased inference on the distribution of compact binaries, it is necessary to account for this selection effect, which is known as Malmquist bias. Since systematic error from selection effects grows with the number of events, it will be increasingly important over the coming years to accurately estimate the observational selection function for gravitational-wave astronomy. We employ a range of machine learning methods to accurately and efficiently compute the compact binary coalescence selection function. We introduce a simple pre-processing method, which significantly reduces the complexity of the required machine learning models. As a demonstration of our method, we reproduce and extend the results from the recent LIGO--Virgo analysis of events from their second gravitational-wave transient catalog (GWTC-2). While qualitatively consistent with previous work, we find that the method used to compute the selection function noticeably affects the inferred population. The most significant change is a 1σ increase in the steepness of the mass ratio distribution and an ∼10% increase in the inferred rate, RBBH=32+11−9Gpc−3yr−1, when using our new method. Including spin effects in the selection function does not significantly impact the results with current uncertainties.

#### Comments

Not sure if this is an interesting use of machine learning or not...

**Comment by fberlato** [comment] 2020-12-03 08:36
### **GRBAlpha: A 1U CubeSat mission for validating timing-based gamma-ray burst localization**

https://arxiv.org/abs/2012.01298

GRBAlpha is a 1U CubeSat mission with an expected launch date in the first half of 2021. It carries a 75 x 75 x 5 mm CsI(Tl) scintillator, read out by a dual-channel multi-pixel photon counter (MPPC) setup, to detect gamma-ray bursts (GRBs). The GRB detector is an in-orbit demonstration for the detector system on the Cubesats Applied for MEasuring and LOcalising Transients (CAMELOT) mission. While GRBAlpha provides 1/8th of the expected effective area of CAMELOT, the comparison of the observed light curves with other existing GRB monitoring satellites will allow us to validate the core idea of CAMELOT, i.e. the feasibility of timing-based localization. 

**Comments**

Not super interesting, as it ends up being mostly about the electronics...

**Closed** 2020-12-07 14:08 UTC
